version: '3.4'

services:
  avanade.it.challengese.api:
    image: ${DOCKER_REGISTRY-}avanadeitchallengeseapi
    build:
      context: .
      dockerfile: Avanade.IT.ChallengeSE.Api/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433

  